services:
  basic-dev:
    image: basic:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ../basic_ws:/workspace/code:rw
      - .ros:/root/.ros:rw
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /workspace/code
    container_name: basic-dev
    command: /bin/bash
    network_mode: host
    stdin_open: true
    tty: true
