FROM ros:humble-ros-base

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    vim \
    python3-colcon-common-extensions \
    ros-humble-geometry-msgs \
    ros-humble-rclcpp-components \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspaces/code
