FROM ros:humble-ros-base

# System deps
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    python3-colcon-common-extensions \
    && rm -rf /var/lib/apt/lists/*

# ROS deps
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-humble-geometry-msgs \
    ros-humble-rclcpp-components \
    && rm -rf /var/lib/apt/lists/*

# Build
COPY ./basic_ws /workspace/code
WORKDIR /workspace/code
RUN . /opt/ros/humble/setup.sh \
    && colcon build \
    && echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc \
    && echo "source /workspace/code/install/setup.bash" >> ~/.bashrc

CMD ["/bin/bash", "-lc", "source /workspace/code/install/setup.bash && exec ros2 launch basic_topic basic_topic.launch.py"]
