FROM ros:humble-ros-base AS builder

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    python3-colcon-common-extensions \
    ros-humble-geometry-msgs \
    ros-humble-rclcpp-components \
    && rm -rf /var/lib/apt/lists/*

COPY basic_ws /workspaces/basic_ws
WORKDIR /workspaces/basic_ws
RUN colcon build

FROM ros:humble-ros-base

RUN apt-get update && apt-get install -y \
    ros-humble-geometry-msgs \
    ros-humble-rclcpp-components \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /workspaces/basic_ws/install /workspaces/install
COPY docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["ros2", "launch", "basic_topic", "basic_topic.launch.py"]
